# Importing the libraries and Raw Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('Raw_Data.xlsx')

In [2]:
df.isnull().sum()

Chennai Super Kings             6
Delhi Capitals                  5
Kings XI Punjab                 4
Kolkata Knight Riders           6
Mumbai Indians                  4
Rajasthan Royals                3
Royal Challengers Bangalore    10
Sunrisers Hyderabad             0
dtype: int64

In [3]:
df.head(10)

,Chennai Super Kings,Delhi Capitals,Kings XI Punjab,Kolkata Knight Riders,Mumbai Indians,Rajasthan Royals,Royal Challengers Bangalore,Sunrisers Hyderabad
0,MS Dhoni,Shreyas Iyer,KL Rahul,Dinesh Karthik,Rohit Sharma,Steven Smith,Virat Kohli,David Warner
1,MS DhoniCaptain/Keeper,Shreyas IyerCaptain,KL RahulCaptain/Keeper,Dinesh KarthikCaptain/Keeper,Rohit SharmaCaptain,Steven SmithOverseas Player,Virat KohliCaptain,David WarnerOverseas Player
2,Age: 38 years 165 daysPlaying role: Wicketkeep...,Age: 25 years 13 daysPlaying role: Top-order b...,Age: 27 years 245 daysPlaying role: Opening ba...,Age: 34 years 201 daysPlaying role: Wicketkeep...,Age: 32 years 233 daysPlaying role: Top-order ...,Age: 30 years 200 daysPlaying role: Middle-ord...,Age: 31 years 44 daysPlaying role: Top-order b...,Age: 33 years 53 daysPlaying role: Opening bat...
3,KM Asif,Ravichandran Ashwin,Mayank Agarwal,Ali Khan,Anmolpreet Singh,Varun Aaron,Moeen Ali,Abdul Samad
4,KM Asif,Ravichandran Ashwin,Mayank Agarwal,Ali KhanOverseas Player,Anmolpreet Singh,Varun Aaron,Moeen AliOverseas Player,Abdul Samad
5,Age: 26 years 148 daysPlaying role: BowlerBatt...,Age: 33 years 93 daysPlaying role: Bowling all...,Age: 28 years 306 daysPlaying role: BatsmanBat...,Age: 29 years 6 daysPlaying role: BowlerBattin...,Age: 21 years 266 daysPlaying role: BatsmanBat...,Age: 30 years 51 daysPlaying role: BowlerBatti...,Age: 32 years 184 daysPlaying role: Batting al...,Age: 18 years 52 daysPlaying role: BatsmanBatt...
6,Dwayne Bravo,Avesh Khan,Arshdeep Singh,Tom Banton,Trent Boult,Akash Singh,Yuzvendra Chahal,Abhishek Sharma
7,Dwayne BravoOverseas Player,Avesh Khan,Arshdeep Singh,Tom BantonOverseas Player,Trent BoultOverseas Player,Akash Singh,Yuzvendra Chahal,Abhishek Sharma
8,Age: 36 years 73 daysPlaying role: AllrounderB...,Age: 23 years 6 daysPlaying role: BowlerBattin...,Age: 20 years 317 daysPlaying role: BowlerBatt...,Age: 21 years 38 daysPlaying role: Opening bat...,Age: 30 years 150 daysPlaying role: BowlerBatt...,Age: 17 years 237 daysPlaying role: BowlerBatt...,Age: 29 years 149 daysPlaying role: BowlerBatt...,Age: 19 years 106 daysPlaying role: BowlerBatt...
9,Deepak Chahar,Alex Carey,Murugan Ashwin,Pat Cummins,Jasprit Bumrah,Anuj Rawat,Pavan Deshpande,Khaleel Ahmed

# Data Preprocessing and Creating features

In [4]:
import re
from re import search
Team = []
Player_Name = []
IsCaptain = []
Playing_Role = []
Age = []
Batting_style= []
Bowling_style = []
IsOverseas = []
IsUncapped= []

pattern = re.compile("Age:")

all_teams = df.columns.tolist()

for team in all_teams:
    for i,j in df[team].dropna().items():
        if search(pattern, j):
            j = j.replace("Playing",",Playing").replace("Batting:", ",Batsman:").replace("Bowling:", ",Bowling:").replace('\xa0',"")
            Team.append(team)
            Player_Name.append(df[team][i-1].replace('Captain/Keeper',"").replace("Captain","").replace('Overseas Player',"").replace('Wicketkeeper', ""))
            Age.append(int(j.split(':')[1].split()[0]) + int(j.split(':')[1].split()[2])/365)
            Playing_Role.append(j.split(':')[2].split(',')[0])
            Batting_style.append(j.split(':')[3].split(',')[0])
            try:
                Bowling_style.append(j.split(':')[4].split(',')[0])
            except IndexError:
                Bowling_style.append('nan')

            if search('Overseas Player', df[team][i-1]):
                IsOverseas.append('Yes')
            else:
                IsOverseas.append('No')

            if search('Captain', df[team][i-1]):
                IsCaptain.append('Yes')
            else:
                IsCaptain.append('No')
        
        
        #Age.append(re.search('[\d,\S,\w,\S,\d]+ days',j))
(Player_Name)

['MS Dhoni',
 'KM Asif',
 'Dwayne Bravo',
 'Deepak Chahar',
 'Piyush Chawla',
 'Sam Curran',
 'Faf du Plessis',
 'Ruturaj Gaikwad',
 'Josh Hazlewood',
 'Imran Tahir',
 'Ravindra Jadeja',
 'Kedar Jadhav',
 'Narayan Jagadeesan',
 'Monu Kumar',
 'Lungi Ngidi',
 'Ambati Rayudu',
 'Ravisrinivasan Sai Kishore',
 'Mitchell Santner',
 'Karn Sharma',
 'Shardul Thakur',
 'Murali Vijay',
 'Shane Watson',
 'Harbhajan SinghWithdrawn Player',
 'Suresh RainaWithdrawn Player',
 'Shreyas Iyer',
 'Ravichandran Ashwin',
 'Avesh Khan',
 'Alex Carey',
 'Tushar Deshpande',
 'Shikhar Dhawan',
 'Shimron Hetmyer',
 'Sandeep Lamichhane',
 'Amit Mishra',
 'Anrich Nortje',
 'Rishabh Pant',
 'Axar Patel',
 'Harshal Patel',
 'Keemo Paul',
 'Kagiso Rabada',
 'Ajinkya Rahane',
 'Daniel Sams',
 'Ishant Sharma',
 'Mohit Sharma',
 'Prithvi Shaw',
 'Marcus Stoinis',
 'Lalit Yadav',
 'Jason RoyWithdrawn Player',
 'Chris WoakesWithdrawn Player',
 'KL Rahul',
 'Mayank Agarwal',
 'Arshdeep Singh',
 'Murugan Ashwin',
 'Sheldon Cottrell',
 'Chris Gayle',
 'Krishnappa Gowtham',
 'Harpreet Brar',
 'Deepak Hooda',
 'Chris Jordan',
 'Sarfaraz Khan',
 'Mandeep Singh',
 'Glenn Maxwell',
 'Mohammed Shami',
 'Mujeeb Ur Rahman',
 'Karun Nair',
 'Darshan Nalkande',
 'James Neesham',
 'Nicholas Pooran',
 'Ishan Porel',
 'Ravi Bishnoi',
 'Simran Singh',
 'Jagadeesha Suchith',
 'Tajinder Singh',
 'Hardus Viljoen',
 'Dinesh Karthik',
 'Ali Khan',
 'Tom Banton',
 'Pat Cummins',
 'Lockie Ferguson',
 'Chris Green',
 'Kuldeep Yadav',
 'Siddhesh Lad',
 'Eoin Morgan',
 'Kamlesh Nagarkoti',
 'Nikhil Naik',
 'Sunil Narine',
 'Prasidh Krishna',
 'Nitish Rana',
 'Andre Russell',
 'Sandeep Warrier',
 'Shivam Mavi',
 'Shubman Gill',
 'Manimaran Siddharth',
 'Rinku Singh',
 'Rahul Tripathi',
 'Varun Chakravarthy',
 'Harry GurneyWithdrawn Player',
 'Pravin TambeWithdrawn Player',
 'Rohit Sharma',
 'Anmolpreet Singh',
 'Trent Boult',
 'Jasprit Bumrah',
 'Rahul Chahar',
 'Nathan Coulter-Nile',
 'Quinton de Kock',
 'Digvijay Deshmukh',
 'Ishan Kishan',
 'Dhawal Kulkarni',
 'Chris Lynn',
 'Mitchell McClenaghan',
 'Mohsin Khan',
 'Hardik Pandya',
 'Krunal Pandya',
 'James Pattinson',
 'Kieron Pollard',
 'Prince Balwant Rai',
 'Anukul Roy',
 'Sherfane Rutherford',
 'Aditya Tare',
 'Saurabh Tiwary',
 'Jayant Yadav',
 'Suryakumar Yadav',
 'Lasith MalingaWithdrawn Player',
 'Steven Smith',
 'Varun Aaron',
 'Akash Singh',
 'Anuj Rawat',
 'Jofra Archer',
 'Jos Buttler',
 'Tom Curran',
 'Shreyas Gopal',
 'Yashasvi Jaiswal',
 'Aniruddha Joshi',
 'Kartik Tyagi',
 'Mahipal Lomror',
 'Mayank Markande',
 'David Miller',
 'Riyan Parag',
 'Ankit Rajpoot',
 'Sanju Samson',
 'Shashank Singh',
 'Ben Stokes',
 'Rahul Tewatia',
 'Oshane Thomas',
 'Andrew Tye',
 'Jaydev Unadkat',
 'Robin Uthappa',
 'Manan Vohra',
 'Virat Kohli',
 'Moeen Ali',
 'Yuzvendra Chahal',
 'Pavan Deshpande',
 'AB de Villiers',
 'Shivam Dube',
 'Aaron Finch',
 'Gurkeerat Singh Mann',
 'Mohammed Siraj',
 'Chris Morris',
 'Pawan Negi',
 'Devdutt Padikkal',
 'Parthiv Patel',
 'Josh Philippe',
 'Shahbaz Ahmed',
 'Navdeep Saini',
 'Dale Steyn',
 'Isuru Udana',
 'Washington Sundar',
 'Umesh Yadav',
 'Adam Zampa',
 'Kane RichardsonWithdrawn Player',
 'David Warner',
 'Abdul Samad',
 'Abhishek Sharma',
 'Khaleel Ahmed',
 'Fabian Allen',
 'Jonny Bairstow',
 'Basil Thampi',
 'Priyam Garg',
 'Shreevats Goswami',
 'Jason Holder',
 'Siddarth Kaul',
 'Bhuvneshwar Kumar',
 'Mohammad Nabi',
 'Shahbaz Nadeem',
 'T Natarajan',
 'Manish Pandey',
 'Rashid Khan',
 'Wriddhiman Saha',
 'Bavanaka Sandeep',
 'Sandeep Sharma',
 'Sanjay Yadav',
 'Vijay Shankar',
 'Billy Stanlake',
 'Virat Singh',
 'Kane Williamson',
 'Mitchell MarshWithdrawn Player']

# Creating the data frame from above results

In [6]:
data = {'Team': Team, 'Player_Name': Player_Name, 'IsCaptain': IsCaptain, 'Age': Age, 'Playing_Role': Playing_Role, 'Batting_style': Batting_style, 'Bowling_style': Bowling_style, 'IsOverseasPlayer': IsOverseas}
Main_df = pd.DataFrame(data, columns = data.keys())
Main_df.head()

,Team,Player_Name,IsCaptain,Age,Playing_Role,Batting_style,Bowling_style,IsOverseasPlayer
0,Chennai Super Kings,MS Dhoni,Yes,38.452055,Wicketkeeper batsman,Right-hand bat,Right-arm medium,No
1,Chennai Super Kings,KM Asif,No,26.405479,Bowler,Right-hand bat,Right-arm medium,No
2,Chennai Super Kings,Dwayne Bravo,No,36.200000,Allrounder,Right-hand bat,Right-arm medium,Yes
3,Chennai Super Kings,Deepak Chahar,No,27.367123,Bowler,Right-hand bat,Right-arm medium,No
4,Chennai Super Kings,Piyush Chawla,No,30.986301,Allrounder,Left-hand bat,Legbreak,No

# Removal of "Withdrawn Players"
Players like Raina and Harbhajan singh withdrew from the team, hence removed form the dataset

In [7]:
Main_df[Main_df['Player_Name']. str.contains('Withdrawn Player')]

,Team,Player_Name,IsCaptain,Age,Playing_Role,Batting_style,Bowling_style,IsOverseasPlayer
22,Chennai Super Kings,Harbhajan SinghWithdrawn Player,No,39.463014,Bowler,Right-hand bat,Right-arm offbreak,No
23,Chennai Super Kings,Suresh RainaWithdrawn Player,No,33.060274,Middle-order batsman,Left-hand bat,Right-arm offbreak,No
46,Delhi Capitals,Jason RoyWithdrawn Player,No,29.413699,Opening batsman,Right-hand bat,nan,No
47,Delhi Capitals,Chris WoakesWithdrawn Player,No,30.800000,Allrounder,Right-hand bat,Right-arm fast-medium,No
95,Kolkata Knight Riders,Harry GurneyWithdrawn Player,No,33.150685,Bowler,Right-hand bat,Left-arm fast-medium,No
96,Kolkata Knight Riders,Pravin TambeWithdrawn Player,No,48.197260,Bowler,Right-hand bat,Legbreak,No
121,Mumbai Indians,Lasith MalingaWithdrawn Player,No,36.309589,Bowler,Right-hand bat,Right-arm fast,No
168,Royal Challengers Bangalore,Kane RichardsonWithdrawn Player,No,28.849315,Bowler,Right-hand bat,Right-arm fast-medium,No
194,Sunrisers Hyderabad,Mitchell MarshWithdrawn Player,No,28.164384,Allrounder,Right-hand bat,Right-arm medium,No

In [8]:
Main_df.drop(Main_df[Main_df['Player_Name']. str.contains('Withdrawn Player')].index,axis=0, inplace=True)
Main_df.reset_index(drop=True,inplace = True)
Main_df[Main_df['Player_Name']. str.contains('Withdrawn Player')].index

Int64Index([], dtype='int64')

# Creating a new feature called 'IsUncapped' and hardcoded this feature and saved this feature

In [9]:
Main_df['IsUncapped'] = 'No'

#Main_df.to_excel('Cleaned_data_backup.xlsx')

# Importing a cleaned data generated from previous steps

In [15]:
Cleaned_df = pd.read_excel('Cleaned_data_backup.xlsx')

In [16]:
Cleaned_df.isnull().sum()

Team                 0
Player_Name          0
IsCaptain            0
Age                  0
Playing_Role         0
Batting_style        0
Bowling_style       20
IsOverseasPlayer     0
IsUncapped           0
dtype: int64

# Further processing of Data for Model building

In [17]:
Overseas = {"Yes": "Overseas Player", "No": "No"}
Captain = {"Yes": "Captain", "No": "No"}
IsUncapped = {"Yes": "Uncapped", "No":"No"}

Cleaned_df['IsOverseasPlayer'] = Cleaned_df['IsOverseasPlayer'].map(Overseas)
Cleaned_df['IsCaptain'] = Cleaned_df['IsCaptain'].map(Captain)
Cleaned_df['IsUncapped'] = Cleaned_df['IsUncapped'].map(IsUncapped)

In [18]:
Cleaned_df['Playing_Role'].unique()

array(['Wicketkeeper batsman', 'Bowler', 'Allrounder',
       'Middle-order batsman', 'Batsman', 'Batting allrounder',
       'Opening batsman', 'Bowling allrounder', 'Top-order batsman',
       'Wicketkeeper'], dtype=object)

In [19]:
Cleaned_df['Playing_Role'] = np.where(Cleaned_df['Playing_Role']=='Wicketkeeper','Wicketkeeper batsman',Cleaned_df['Playing_Role'])
Cleaned_df['Playing_Role'] = np.where(Cleaned_df['Playing_Role']=='Allrounder','Bowling allrounder',Cleaned_df['Playing_Role'])

In [20]:
Cleaned_df['Playing_Role'].unique()

array(['Wicketkeeper batsman', 'Bowler', 'Bowling allrounder',
       'Middle-order batsman', 'Batsman', 'Batting allrounder',
       'Opening batsman', 'Top-order batsman'], dtype=object)

In [23]:
Cleaned_df[Cleaned_df['IsOverseasPlayer']=='Overseas Player'].head()

,Team,Player_Name,IsCaptain,Age,Playing_Role,Batting_style,Bowling_style,IsOverseasPlayer,IsUncapped
2,Chennai Super Kings,Dwayne Bravo,No,36.200000,Bowling allrounder,Right-hand bat,Right-arm medium,Overseas Player,No
5,Chennai Super Kings,Sam Curran,No,21.545205,Bowling allrounder,Left-hand bat,Left-arm medium-fast,Overseas Player,No
6,Chennai Super Kings,Faf du Plessis,No,35.435616,Middle-order batsman,Right-hand bat,Legbreak,Overseas Player,No
8,Chennai Super Kings,Josh Hazlewood,No,28.945205,Bowler,Left-hand bat,Right-arm fast-medium,Overseas Player,No
9,Chennai Super Kings,Imran Tahir,No,40.731507,Bowler,Right-hand bat,Legbreak googly,Overseas Player,No

# The team should have 4 batsmen, 2 allrounders, 1 wicketkeeper and 4 bowlers. There should also be 4 overseas players and 1 uncapped player (player of Indian origin who hasn’t played for the national team yet) in the team

In [25]:
Cleaned_df[Cleaned_df['Team']=='Chennai Super Kings'].head()

,Team,Player_Name,IsCaptain,Age,Playing_Role,Batting_style,Bowling_style,IsOverseasPlayer,IsUncapped
0,Chennai Super Kings,MS Dhoni,Captain,38.452055,Wicketkeeper batsman,Right-hand bat,Right-arm medium,No,No
1,Chennai Super Kings,KM Asif,No,26.405479,Bowler,Right-hand bat,Right-arm medium,No,Uncapped
2,Chennai Super Kings,Dwayne Bravo,No,36.200000,Bowling allrounder,Right-hand bat,Right-arm medium,Overseas Player,No
3,Chennai Super Kings,Deepak Chahar,No,27.367123,Bowler,Right-hand bat,Right-arm medium,No,No
4,Chennai Super Kings,Piyush Chawla,No,30.986301,Bowling allrounder,Left-hand bat,Legbreak,No,No

In [26]:
Cleaned_df[(Cleaned_df['IsOverseasPlayer']=='No')&(Cleaned_df['IsUncapped']=='Uncapped')].groupby('Team')['Age'].max()

Team
Chennai Super Kings            26.405479
Delhi Capitals                 29.071233
Kings XI Punjab                31.164384
Kolkata Knight Riders          28.800000
Mumbai Indians                 32.115068
Rajasthan Royals               32.115068
Royal Challengers Bangalore    30.257534
Sunrisers Hyderabad            30.589041
Name: Age, dtype: float64

In [27]:
Cleaned_df[(Cleaned_df['IsOverseasPlayer']=='No')&(Cleaned_df['IsUncapped']=='No')].groupby('Team')['Age'].describe()

,count,mean,std,min,25%,50%,75%,max
Team,,,,,,,,
Chennai Super Kings,9.0,32.540335,3.594846,27.367123,30.986301,32.156164,34.734247,38.452055
Delhi Capitals,10.0,29.171233,5.532656,20.109589,25.254795,31.273973,32.825342,37.068493
Kings XI Punjab,4.0,28.459589,0.739267,27.671233,27.944521,28.436986,28.952055,29.293151
Kolkata Knight Riders,3.0,26.614612,7.269059,20.279452,22.646575,25.013699,29.782192,34.550685
Mumbai Indians,7.0,29.214873,2.433567,26.035616,27.464384,29.906849,30.497260,32.638356
Rajasthan Royals,4.0,29.379452,3.770149,25.104110,27.403425,29.154795,31.130822,34.104110
Royal Challengers Bangalore,10.0,27.895890,4.132540,20.205479,25.947945,27.010959,30.692466,34.780822
Sunrisers Hyderabad,6.0,29.302740,4.207400,22.038356,29.068493,29.727397,30.172603,35.153425

In [28]:
percent = pd.DataFrame(Cleaned_df[(Cleaned_df['IsOverseasPlayer']=='No')&(Cleaned_df['IsUncapped']=='Uncapped')].groupby('Team')['Age'].describe())
percent.loc['Chennai Super Kings']['75%']

25.12054794520548

# Saving the file and reading again

In [29]:

#Cleaned_df.to_excel('IPL_Team_11\Final_excel.xlsx')

In [30]:
Cleaned_df = pd.read_excel('IPL_Team_11\Final_excel.xlsx')

In [41]:
#"1 for Chennai Super Kings"
#"2 for Delhi Capitals"
#"3 for Kings XI Punjab"
#"4 for Kolkata Knight Riders"
#"5 for Mumbai Indians"
#"6 for Rajasthan Royals"
#"7 for Royal Challengers Bangalore"
#"8 for Sunrisers Hyderabad"

Team_Dictionary = {1:"Chennai Super Kings", 2: "Delhi Capitals", 3: "Kings XI Punjab",4:"Kolkata Knight Riders", 5:"Mumbai Indians",6:"Rajasthan Royals",7: "Royal Challengers Bangalore",8:"Sunrisers Hyderabad"}

selection = int(input("Enter a number based on team :"))

team_name = Team_Dictionary.get(selection)
team_df = Cleaned_df[Cleaned_df['Team']== team_name]  
team_df.head()

Enter a number based on team :1

,Team,Player_Name,IsCaptain,Age,Playing_Role,Batting_style,Bowling_style,IsOverseasPlayer,IsUncapped
0,Chennai Super Kings,MS Dhoni,Captain,38.452055,Wicketkeeper batsman,Right-hand bat,Right-arm medium,No,No
1,Chennai Super Kings,KM Asif,No,26.405479,Bowler,Right-hand bat,Right-arm medium,No,Uncapped
2,Chennai Super Kings,Dwayne Bravo,No,36.200000,Bowling allrounder,Right-hand bat,Right-arm medium,Overseas Player,No
3,Chennai Super Kings,Deepak Chahar,No,27.367123,Bowler,Right-hand bat,Right-arm medium,No,No
4,Chennai Super Kings,Piyush Chawla,No,30.986301,Bowling allrounder,Left-hand bat,Legbreak,No,No

# Failed model

In [37]:
import random

n = 10
A = list(i for i, j in team_df.iterrows() )
k = 11
m = 100

My_team_11_index = []

while len(My_team_11_index)==0:
    samples = list()
    tries = 0

    while len(samples) < m:
        samples.append(list(sorted(random.sample(A, k))))
        tries += 1

    for sample in samples:
        q = team_df.loc[sample].groupby('IsCaptain')['IsCaptain'].count()
        r = team_df.loc[sample].groupby('Playing_Role')['Playing_Role'].count()
        s = team_df.loc[sample].groupby('IsOverseasPlayer')['IsOverseasPlayer'].count()
        t = team_df.loc[sample].groupby('IsUncapped')['IsUncapped'].count()
        try:
            if q['Captain'] == 1:
                if r['Opening batsman']==1:
                    if r['Batsman']==1:
                        if r['Middle-order batsman']<3:
                            if r['Wicketkeeper batsman']==1:
                                if r['Batting allrounder']<2:
                                    if r['Bowling allrounder']==1:
                                        if r['Bowler']==4:
                                            if s['Overseas Player']==4:
                                                if t['Uncapped']<5:
                                                    My_team_11_index = samples
        except KeyError:
            pass
#print(samples)
print(My_team_11_index)

In [40]:
team_df.loc[My_team_11_index]

KeyError: 'None of [[[1, 3, 4, 12, 13, 14, 15, 16, 17, 18, 21], [0, 1, 3, 5, 9, 10, 12, 13, 17, 18, 20], [1, 3, 5, 6, 7, 8, 9, 12, 16, 19, 21], [0, 4, 5, 6, 8, 12, 16, 17, 18, 19, 20], [3, 6, 7, 8, 9, 10, 11, 12, 13, 17, 21], [0, 1, 3, 5, 7, 9, 12, 18, 19, 20, 21], [1, 2, 4, 5, 6, 7, 9, 10, 11, 16, 17], [0, 1, 3, 6, 9, 13, 14, 17, 19, 20, 21], [0, 2, 5, 6, 7, 11, 13, 14, 16, 17, 19], [0, 1, 4, 6, 8, 9, 10, 12, 14, 15, 17], [0, 2, 4, 6, 9, 12, 13, 14, 17, 19, 20], [0, 3, 5, 6, 11, 12, 13, 17, 18, 20, 21], [0, 4, 5, 6, 10, 11, 13, 15, 18, 19, 20], [0, 1, 2, 3, 8, 10, 14, 15, 18, 20, 21], [2, 3, 4, 7, 9, 10, 12, 15, 18, 20, 21], [0, 1, 3, 5, 6, 9, 11, 14, 15, 17, 20], [3, 6, 7, 8, 9, 11, 12, 14, 16, 18, 21], [0, 2, 5, 6, 9, 11, 13, 14, 17, 18, 21], [0, 2, 3, 4, 9, 10, 13, 14, 18, 19, 21], [0, 1, 2, 5, 9, 11, 12, 14, 16, 17, 21], [4, 5, 7, 9, 11, 12, 13, 14, 15, 17, 20], [2, 4, 6, 7, 8, 11, 12, 13, 15, 17, 19], [0, 3, 4, 5, 6, 7, 8, 10, 12, 13, 14], [1, 2, 3, 6, 9, 10, 11, 13, 14, 19, 21], [0, 1, 6, 7, 8, 12, 14, 15, 16, 19, 20], [0, 1, 2, 7, 9, 11, 13, 16, 17, 20, 21], [0, 3, 4, 7, 8, 10, 13, 15, 16, 17, 21], [0, 1, 3, 4, 5, 6, 7, 11, 12, 15, 18], [1, 2, 3, 5, 6, 8, 11, 15, 17, 18, 20], [0, 2, 3, 4, 6, 9, 10, 14, 16, 17, 20], [0, 1, 3, 5, 7, 8, 9, 12, 16, 18, 20], [0, 1, 2, 3, 6, 8, 10, 13, 15, 20, 21], [2, 3, 4, 5, 6, 8, 10, 11, 12, 16, 19], [0, 1, 4, 6, 7, 8, 14, 15, 17, 18, 19], [2, 6, 7, 10, 11, 14, 17, 18, 19, 20, 21], [2, 3, 4, 6, 9, 10, 11, 12, 13, 15, 21], [3, 4, 5, 7, 8, 9, 13, 14, 15, 16, 20], [0, 2, 3, 4, 5, 7, 13, 15, 17, 18, 19], [0, 4, 5, 6, 8, 9, 11, 12, 14, 15, 21], [0, 2, 3, 4, 5, 7, 9, 11, 12, 13, 15], [0, 1, 2, 6, 7, 9, 10, 11, 14, 17, 19], [4, 5, 6, 8, 10, 12, 13, 14, 16, 20, 21], [2, 3, 5, 6, 8, 12, 14, 15, 16, 17, 20], [2, 3, 4, 6, 7, 10, 11, 12, 15, 17, 19], [2, 4, 6, 7, 8, 11, 13, 15, 17, 18, 21], [1, 4, 5, 8, 9, 10, 13, 15, 19, 20, 21], [1, 4, 7, 9, 10, 15, 16, 17, 18, 20, 21], [0, 1, 2, 4, 10, 11, 13, 15, 17, 20, 21], [1, 2, 3, 5, 10, 11, 13, 16, 18, 20, 21], [0, 1, 2, 3, 10, 11, 13, 14, 15, 16, 18], [0, 7, 8, 10, 11, 13, 14, 15, 16, 17, 21], [0, 4, 5, 6, 8, 9, 10, 12, 13, 16, 17], [4, 5, 6, 8, 10, 12, 13, 14, 15, 18, 21], [1, 2, 4, 6, 7, 8, 11, 12, 17, 19, 20], [0, 2, 5, 7, 9, 13, 14, 15, 17, 19, 20], [0, 3, 4, 7, 9, 11, 14, 15, 17, 20, 21], [1, 3, 9, 10, 12, 13, 14, 16, 17, 18, 20], [0, 2, 3, 4, 10, 14, 16, 17, 18, 20, 21], [1, 3, 6, 10, 11, 12, 13, 15, 16, 18, 20], [0, 1, 3, 7, 8, 10, 12, 14, 16, 19, 20], [1, 2, 3, 5, 6, 8, 11, 13, 14, 15, 20], [0, 1, 7, 9, 10, 12, 14, 15, 17, 18, 19], [1, 4, 5, 6, 8, 9, 10, 11, 16, 17, 18], [0, 1, 2, 3, 5, 6, 7, 9, 13, 17, 18], [2, 5, 6, 7, 9, 10, 14, 15, 16, 18, 21], [1, 2, 5, 6, 7, 9, 14, 15, 18, 19, 21], [2, 3, 5, 6, 9, 11, 12, 13, 14, 15, 18], [0, 2, 4, 5, 10, 12, 14, 16, 17, 19, 21], [0, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16], [3, 4, 5, 7, 8, 9, 12, 13, 17, 18, 20], [0, 3, 4, 6, 10, 11, 13, 16, 19, 20, 21], [0, 3, 4, 5, 6, 8, 11, 14, 18, 19, 21], [1, 3, 4, 9, 11, 14, 17, 18, 19, 20, 21], [1, 3, 4, 5, 9, 11, 12, 13, 16, 18, 21], [2, 4, 6, 7, 10, 13, 15, 17, 18, 19, 20], [2, 4, 7, 8, 9, 10, 13, 14, 17, 20, 21], [4, 5, 7, 9, 10, 11, 14, 16, 17, 19, 20], [0, 1, 2, 8, 10, 14, 15, 17, 18, 20, 21], [2, 5, 7, 9, 11, 14, 15, 16, 17, 18, 20], [1, 3, 6, 7, 9, 11, 13, 17, 18, 19, 20], [0, 1, 2, 5, 8, 13, 15, 16, 17, 18, 19], [1, 3, 7, 8, 10, 11, 12, 13, 16, 17, 20], [2, 3, 4, 5, 6, 7, 8, 9, 13, 16, 18], [0, 1, 2, 4, 6, 8, 14, 15, 16, 18, 21], [1, 2, 4, 10, 11, 12, 14, 16, 18, 20, 21], [0, 1, 2, 6, 8, 10, 13, 15, 16, 17, 19], [3, 5, 7, 8, 9, 10, 12, 14, 17, 20, 21], [3, 4, 6, 7, 8, 10, 12, 15, 16, 17, 18], [0, 2, 4, 5, 7, 10, 15, 16, 17, 18, 20], [0, 3, 6, 7, 9, 11, 14, 15, 16, 17, 20], [0, 2, 3, 4, 5, 6, 8, 11, 13, 18, 21], [0, 1, 4, 5, 8, 9, 10, 12, 13, 14, 20], [0, 2, 3, 4, 5, 6, 10, 11, 17, 18, 19], [0, 1, 3, 10, 12, 13, 14, 16, 17, 20, 21], [0, 1, 3, 4, 5, 9, 11, 12, 14, 15, 20], [0, 1, 2, 3, 4, 5, 7, 11, 15, 16, 18], [1, 3, 6, 7, 8, 10, 11, 13, 14, 16, 18], [1, 2, 5, 6, 7, 9, 13, 14, 16, 18, 20], [1, 2, 3, 4, 7, 8, 10, 11, 13, 18, 21], [1, 4, 8, 11, 12, 14, 15, 16, 17, 18, 19]]] are in the [index]'

# New model

In [36]:
team_df = Cleaned_df[Cleaned_df['Team']== team_name] 
A = list(i for i, j in team_df[team_df['IsCaptain']=='Captain'].iterrows())
B = list(i for i, j in team_df[(team_df['Playing_Role']=='Opening batsman')|(team_df['Playing_Role']=='Top-order batsman')|(team_df['Playing_Role']=='Batsman')|(team_df['Playing_Role']=='Middle-order batsman')].iterrows())
C = list(i for i, j in team_df[(team_df['Playing_Role']=='Batting allrounder')|(team_df['Playing_Role']=='Bowling allrounder')].iterrows())
D = list(i for i, j in team_df[team_df['Playing_Role']=='Bowler'].iterrows())
E = list(i for i, j in team_df[team_df['Playing_Role']=='Wicketkeeper batsman'].iterrows())

My_team_11_index = []

while len(My_team_11_index)==0:
    samples = []
    samples.append((sorted(random.sample(A, 1))))

    if A[0] in B:
        B.remove(A[0])
        samples.append((sorted(random.sample(B, 3))))
    else:
        samples.append((sorted(random.sample(B, 3))))

    if team_df.loc[A]['Playing_Role'].item()!='Wicketkeeper batsman':
        samples.append((sorted(random.sample(E, 1))))
        samples.append((sorted(random.sample(C, 2))))
    else:  
        samples.append((sorted(random.sample(C, 3))))

    samples.append((sorted(random.sample(D, 4))))

    samples = [j for i in samples for j in i]

    s = team_df.loc[samples].groupby('IsOverseasPlayer')['IsOverseasPlayer'].count()
    t = team_df.loc[samples].groupby('IsUncapped')['IsUncapped'].count()
    try:
        if s['Overseas Player']==4:
            if t['Uncapped']<4:
                My_team_11_index = samples
    except KeyError:
        continue
        
Final_prediction = [j for j in team_df.loc[My_team_11_index]['Player_Name']]
Final_prediction

['MS Dhoni',
 'Faf du Plessis',
 'Narayan Jagadeesan',
 'Ambati Rayudu',
 'Piyush Chawla',
 'Sam Curran',
 'Ravindra Jadeja',
 'Deepak Chahar',
 'Imran Tahir',
 'Lungi Ngidi',
 'Shardul Thakur']

In [35]:
team_df.loc[samples].groupby('IsUncapped')['IsUncapped'].count()

IsUncapped
No          9
Uncapped    2
Name: IsUncapped, dtype: int64

In [112]:
Cleaned_df[Cleaned_df['Team']=='Kings XI Punjab'].groupby('Playing_Role')['Playing_Role'].count()

Playing_Role
Batsman                  1
Batting allrounder       2
Bowler                  12
Bowling allrounder       5
Middle-order batsman     1
Opening batsman          1
Top-order batsman        1
Wicketkeeper batsman     2
Name: Playing_Role, dtype: int64